# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for Example
  pod 'SuperPlayer', :path => '../SuperPlayer.podspec', :subspecs => ['Player']
  pod 'MBProgressHUD'
  pod 'CFDanmaku', '~> 0.0.1'
  pod 'Bugly'
end
