# Define a global platform for your project
platform :ios, '11.0'

# 共享的基础依赖
def shared_pods
  pod 'SDWebImage'
  pod 'Masonry'
end

target 'Player' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  shared_pods
  # Pods for Player
  pod 'SuperPlayer/Player',:path => '../../SuperPlayerKit/'
  pod 'PlayerKit/Player',:path => '../PlayerKit/'
  
  # Pods for Player_Premium
  #pod 'SuperPlayer/Player_Premium',:path => '../../SuperPlayerKit/'
  #pod 'PlayerKit/Player_Premium',:path => '../PlayerKit/'
end

#target 'Player_Premium' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#  
#  shared_pods
#  # Pods for Player_Premium - 只使用 Premium SDK，避免框架冲突
#  pod 'SuperPlayer/Player_Premium',:path => '../../SuperPlayerKit/'
#  pod 'PlayerKit/Player_Premium',:path => '../PlayerKit/'
#  
#  # 明确排除普通版本的 SDK 以避免冲突
#  pod 'TXLiteAVSDK_Player_Premium'
#end

# 加载框架冲突修复脚本
require_relative 'fix_framework_conflict.rb'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
  
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
  # 调用框架冲突修复函数
  fix_framework_conflicts(installer)
end
