# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftCallOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXLiteAVDemo_Professional
  pod 'TXLiteAVSDK_Player', '~> 10.9.13161'
end

