# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

def tx_im
   pod 'TXIMSDK_iOS'
end

def swift_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'Toast-Swift'
  pod 'Material'
  pod 'NVActivityIndicatorView'
end

def common_pods_all
  pod 'Bugly' # 检测bug使用，非必须依赖
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'CWStatusBarNotification', '~> 2.3.5'
  pod 'TXLiteAVSDK_Player', '~> 11.3.14327'
end

def common_pods_smart
  pod 'CWStatusBarNotification', '~> 2.3.5'
end

def player_pods(subName)
  pod 'SuperPlayer', :path => './TXLiteAVDemo/SuperPlayerKit/SuperPlayer.podspec', :subspecs => ["#{subName}"]
end

target 'TXLiteAVDemo_Player' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXLiteAVDemo_Player
  common_pods_all
  player_pods 'Player'
end
